### ISSUE TITLE
build artifacts on release

### ISSUE THREAD

**Issue by jkowalleck** [k4cg/nichtparasoup#217]
have the build artifacts added to the release

maybe add this to the publish yob
```yaml
      - name: Upload release asset to GitHub
        # use https://github.com/actions/upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: Distribution packages
          asset_path: dist
```
